// @generated by `pnpm sync:web-engine` — DO NOT EDIT THIS COPY.
// Synced from packages/forest-world/src/hex.ts in the storytree parent repo (the
// shared forest-world render core, ADR-0093). Edit the core there and re-sync; a
// stale copy fails the parent's `check:web-engine` gate.

// Hex grid (pointy-top, axial coordinates) — the lattice the forest world's
// territories grow on, plus the small SVG-path helpers the cells/coast render
// from. Pure geometry, browser-safe; the constants here are the studio's
// CANONICAL numbers (the studio wins every divergence from the website seed,
// ADR-0093).

export interface Pt {
  x: number;
  y: number;
}

export interface Axial {
  q: number;
  r: number;
}

export const HEX_R = 27; // centre → corner
export const HEX_W = Math.sqrt(3) * HEX_R;
export const TILE_DEPTH = 8; // extrusion below a claimed tile

export const axialKey = (h: Axial): string => `${h.q},${h.r}`;

/** Neighbour directions, indexed so AXIAL_DIRS[i] faces the edge corner i → i+1. */
export const AXIAL_DIRS: Axial[] = [
  { q: 1, r: -1 }, // NE  (edge between corners 0 and 1)
  { q: 1, r: 0 }, //  E  (1 → 2)
  { q: 0, r: 1 }, //  SE (2 → 3)
  { q: -1, r: 1 }, // SW (3 → 4)
  { q: -1, r: 0 }, // W  (4 → 5)
  { q: 0, r: -1 }, // NW (5 → 0)
];

export function hexCenter(h: Axial): Pt {
  return { x: HEX_W * (h.q + h.r / 2), y: 1.5 * HEX_R * h.r };
}

export function pixelToHex(p: Pt): Axial {
  const rf = p.y / (1.5 * HEX_R);
  const qf = p.x / HEX_W - rf / 2;
  const sf = -qf - rf;
  let q = Math.round(qf);
  let r = Math.round(rf);
  const s = Math.round(sf);
  const dq = Math.abs(q - qf);
  const dr = Math.abs(r - rf);
  const ds = Math.abs(s - sf);
  if (dq > dr && dq > ds) q = -r - s;
  else if (dr > ds) r = -q - s;
  return { q, r };
}

export function hexDist(a: Axial, b: Axial): number {
  return (Math.abs(a.q - b.q) + Math.abs(a.q + a.r - b.q - b.r) + Math.abs(a.r - b.r)) / 2;
}

/** The six corners around (cx, cy), corner 0 at the top, clockwise. */
export function hexCorners(cx: number, cy: number, R: number): Pt[] {
  const pts: Pt[] = [];
  for (let i = 0; i < 6; i++) {
    const a = (Math.PI / 180) * (60 * i - 90);
    pts.push({ x: cx + R * Math.cos(a), y: cy + R * Math.sin(a) });
  }
  return pts;
}

export function hexPath(cx: number, cy: number, R: number): string {
  return (
    hexCorners(cx, cy, R)
      .map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`)
      .join(' ') + ' Z'
  );
}

/** A closed polygon `d` string. */
export function polyPath(pts: Pt[]): string {
  if (pts.length === 0) return '';
  return (
    pts.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ') + ' Z'
  );
}
